### PR TITLE
Isomorphic Flux

### PR DESCRIPTION
**Pull request by mridgway**
Flux provides a good framework for building rich client applications, but did you know you can reuse the flux architecture for server rendering? In this talk, I'll walk you through an isomorphic Flux architecture to give you the holy grail of frontend development. With this architecture you'll be able to reuse all of your application code on the server and client without worrying about server-side concurrency issues that you may see with stock Flux.

Once the concepts have been explained, I will introduce the libraries that we have open sourced and are powering many of Yahoo's high-traffic web applications.

### CODE REVIEW

**Comment by fisherwebdev** [comment]
:+1:

**Comment by kennydee** [comment]
:+1:

**Comment by rickbeerendonk** [comment]
:+1:

**Comment by nuc-gr** [comment]
:

**Comment by nuc** [comment]
:+1:

**Comment by sejoker** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Pull request merged**
