### PR TITLE
Building the worlds largest grocery shopping site with React

### PR DESCRIPTION
**Pull request by StuartHarris**
Tesco is the world’s third largest retailer, handling half the world’s online grocery shopping.
React has transformed UI engineering at Tesco and helped the retailer build large scale isomorphic applications that are fast to run and quick to build.
Tesco recently released a fully isomorphic grocery home shopping service for mobile devices in Poland, Turkey, Hungary, Slovakia, Czech Republic, Malaysia and Thailand. It’s built with React.js and Node.js. 
Stu is CTO at Red Badger and has been a TA at Tesco since early 2014. He will look at the techniques that have been used so far, how they’re evolving and how the use of immutable data and cursors is helping to enhance the user experience and speed up and simplify development.
Red Badger is also building and maintaining Reflex, an open source framework that makes it easy to create fully isomorphic applications with React using centralised state.
Stu will cover how this framework distills our learnings and can help you structure new isomorphic applications and gain all the benefits of using a single immutable data structure to manage your application state.

### CODE REVIEW

**Comment by AmyBadger** [comment]
+1

**Comment by robbiemccorkell** [comment]
+1

**Comment by tabazevedo** [comment]
:+1:

**Comment by scarerkite** [comment]
+1

**Comment by ukpeti** [comment]
+1

**Comment by jameshopkins** [comment]
+1

**Comment by dpiatek** [comment]
:+1:

**Comment by musshush** [comment]
:+1:

**Comment by charypar** [comment]
:+1:

**Comment by albertstill** [comment]
:+1:

**Comment by ajcumine** [comment]
:+1:

**Comment by dwynne** [comment]
:+1:

**Comment by JoeStanton** [comment]
:+1:

**Comment by cainullah** [comment]
+1

**Comment by dougmcclurg** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
