### PR TITLE
Visual Musical Systems With React

### PR DESCRIPTION
**Pull request by jergason**
In React you model your app as a tree of components. Data flows down through the tree to update your app. The Web Audio API enables you to create sound by building a graph of AudioNodes. Signals flow through the graph, are modified at each node, and comes out your speakers. These two things are very similar! React is a great fit for building a music creation tool.

Learn the basics of the Web Audio API, and how we can use React to make and visualize music in the browser. Along the way we'll talk about unique strategies for component communication, and together we will compose and perform The Song Of React.

### CODE REVIEW

**Comment by gaearon** [comment]
YES PLEASE.

**Comment by mzabriskie** [comment]
👍

**Comment by matma** [comment]
:+1:

**Comment by jlongster** [comment]
👍

**Comment by olegafx** [comment]
:+1:

**Comment by SerenadeX** [comment]
👍

**Comment by Hossman333** [comment]
:thumbsup:

**Comment by Rob-ot** [comment]
:+1:

**Comment by neoncrumpet** [comment]
:+1:

**Comment by sejoker** [comment]
:+1:

**Comment by chantastic** [comment]
:+1:

**Comment by pletcher** [comment]
:+1: This sounds (no pun intended) so cool

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
