### PR TITLE
Visualizing React

### PR DESCRIPTION
**Pull request by banderson**
Want to better understand the "magic" behind your React applications?
We'll help uncover React's inner workings with three custom-built demos that
highlight core react features (DOM Diffing, Synthetic Events, Data Flow) in
a visual way, to help developers truly "grok" what's happening under the
hood of their React-backed applications.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
:+1:

**Comment by joshschumacher** [comment]
:+1:

**Comment by kevinrobinson** [comment]
:+1:

**Comment by jedcn** [comment]
:+1:

**Comment by timmfin** [comment]
:+1:

**Comment by gaearon** [comment]
:+1: great idea

**Comment by chantastic** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn't an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
