### PR TITLE
Lessons from Om with a Key to Plato

### PR DESCRIPTION
**Pull request by pletcher**
One of the chief problems that React solves is the issue of knowledge about state. In Plato's _Theaetetus_, Socrates solves a similar problem: How do we distinguish knowledge that we have (ἔχω) from knowledge that we possess (κτάομαι)? The problem in both cases is compounded by the fact that knowledge — how a person looks or whether `on === true` — changes over time.

In this talk, I want to show how Om (the ClojureScript interface to React) and core.async teach us about immutable data in ways that benefit even pure JavaScript applications. By focusing on Flux-y architectural patterns in pure JavaScript and in Om using core.async channels, I'll show that we know our data best not by keeping it from changing but by having justified true knowledge about its changes. I'll also demonstrate how we can use transducers to keep state comprehensible as it moves from actions to stores.

### CODE REVIEW

**Comment by nb** [comment]
:+1:

**Comment by whatupdave** [comment]
This sounds awesome!

**Comment by chrislloyd** [comment]
:+1:

**Comment by awwstn** [comment]
I love it! :+1:

**Comment by gaearon** [comment]
:+1:

**Comment by bshyong** [comment]
:+1:

**Comment by vanstee** [comment]
:+1:

**Comment by brian-github** [comment]
:+1:

**Comment by Swankhunt** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn't an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
