### PR TITLE
Testing React components the right way

### PR DESCRIPTION
**Pull request by NiGhTTraX**
Did you ever introduce a mistake in the `render()` method and have your
tests that check the callbacks fail? Did you ever introduce a mistake in one
of your component's children and have the parent's tests fail? Is your test
suite slow and to work around it you only run part of it?

I answered yes to all of those questions a while ago and I was very
frustrated. So I decided to rewrite our testing framework from the ground
up. We managed to transition from slow running integrated tests to fast
highly focused tests. Now when a mistake is introduced into a component,
only the relevant tests fail and we immediately know where to debug.

In this presentation I'll talk about the theory of collaboration and
contract tests and how we can apply it to React components. I'll then delve
into the techniques we use to write tests that only check the behaviour that
we want to check.

### CODE REVIEW

**Comment by gaearon** [comment]
You may find this interesting (if you haven't seen it already): https://github.com/facebook/react/pull/2963/files

**Comment by NiGhTTraX** [comment]
@gaearon nice. It seems to partially solve the problem of children interfering with your parent's tests, but we've taken it a step further :)

**Comment by emmenko** [comment]
:+1:

**Comment by RadValentin** [comment]
:+1:

**Comment by catalinmiron** [comment]
:+1:

**Comment by chris-ramon** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
