### PR TITLE
Dawn of the Progressive Single Page App

### PR DESCRIPTION
**Pull request by markdalgleish**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
:+1:

**Comment by mattdelacdev** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by jwswj** [comment]
Love it! :+1:

**Comment by wmaurer** [comment]
:+1:

**Comment by davidduffett** [comment]
:+1:

**Comment by michaeltaranto** [comment]
:+1:

**Comment by plasticine** [comment]
:+1:

**Comment by amindunited** [comment]
:+1:

**Comment by knuton** [comment]
:+1:

**Comment by NicoVerkest** [comment]
:+1:

**Comment by sejoker** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Comment by markdalgleish** [comment]
Thanks @patcito for considering my talk—the final lineup looks amazing :+1:

**Pull request closed without merging**
