### PR TITLE
Flux over the Wire

### PR DESCRIPTION
**Pull request by elierotenberg**
My talk proposal :)

### CODE REVIEW

**Comment by gaearon** [comment]
Awesome, I want to see that!

**Comment by elierotenberg** [comment]
https://github.com/elierotenberg/nexus-flux Here's a glimpse of what I'm talking about!

**Comment by elierotenberg** [comment]
http://codepen.io/elierotenberg/blog/flux-over-the-wire More about this stuff!

**Comment by elierotenberg** [comment]
http://blog.rotenberg.io/flux-over-the-wire-3/
http://blog.rotenberg.io/million-user-webchat-with-full-stack-flux-react-redis-and-postgresql/

More! I hope you find this interesting :)

**Comment by gaearon** [comment]
:+1: This is all very interesting

**Comment by vjeux** [comment]
Some nice comments on Hacker News as well. https://news.ycombinator.com/item?id=9020318

**Comment by eTorAken** [comment]
Very interesting!

**Comment by Hadrien-DELAITRE** [comment]
:+1: Thanks ! It's really good

**Comment by glaciuspgm** [comment]
Nice :+1:

**Comment by dargor** [comment]
I'm looking forward to this talk ! :+1:

**Comment by massimiliano-mantione** [comment]
:+1:+1
I really want to see this! :smile:

**Comment by knuton** [comment]
:+1:

**Comment by jergason** [comment]
Looks neato!

**Comment by sejoker** [comment]
:+1:

**Comment by pletcher** [comment]
I've been referencing https://blog.rotenberg.io/million-user-webchat-with-full-stack-flux-react-redis-and-postgresql/ frequently over the past couple of weeks -- really excited for this stuff :) :+1:

**Pull request merged**
