### PR TITLE
Event-Sourcing your React Applications

### PR DESCRIPTION
**Pull request by mauricedb**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
:+1: event sourcing is awesome. Immutability is even more needed on the backend.

**Comment by gaearon** [comment]
:+1: would love to learn more

**Comment by mauricedb** [comment]
And I would love to show you more :-)

**Comment by gaearon** [comment]
Sad it's not passed. Do you plan to write any articles about it?

**Comment by markdalgleish** [comment]
:+1:

**Comment by mauricedb** [comment]
@gaearon I guess it hasn't as the CFP is closed and a lot of other talks have been accepted. Still a slimmer of hope though as I haven't really been rejected either as quite a few other talks have been.

I will blog about using Event Sourcing and there are some other good sources out there as well. Additionally you can watch a similar lightning talk I recently did at the Dutch Angular conference on the same subject here: https://www.youtube.com/watch?v=NAhJmyiKqhc Its just a 20 minute talk though so no code, just concepts. The slides are [here](http://www.slideshare.net/mauricedb/event-sourcing-your-angularjs-applications) with notes and links in the sheets comments.

**Comment by gaearon** [comment]
Nice, thank you!

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
