### PR TITLE
Awesome Animations in React

### PR DESCRIPTION
**Pull request by nmn**
Building apps with amazing animations by learning lessons from the famo.us framework.

### CODE REVIEW

**Comment by squeaky-pl** [comment]
+1

**Comment by fcofdez** [comment]
+1

**Comment by robgraeber** [comment]
+1

**Comment by Aracem** [comment]
+1

**Comment by fastestOrange** [comment]
+1

**Comment by auser** [comment]
+1

**Comment by 0xjocke** [comment]
+1

**Comment by sejoker** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Comment by nmn** [comment]
Thanks for the nice message. How long will the lightening talks be?

**Pull request closed without merging**
