### PR TITLE
Managing complexity in large reactive applications

### PR DESCRIPTION
**Pull request by laszlopandy**
React has changed how we develop user interfaces, but there are
lots of competing ideas about how the rest of the application
should interact. We faced this when building our presentation tool
using React. It needs to handle lots of state, complex mouse
interactions and communication with our canvas renderer. Not to
mention the fact that users expect our app to support
Google Docs-style collaboration and so we also have to react to
changes from the network seamlessly.

To manage this complexity we tried using OOP, Flux, FRP (Bacon.js)
and we even tried reimplementing parts in Elm.
In this talk I will show you what we learned and how we decided
to mix architectures. I will demonstrate how they interact
while taking advantage of centralized state and pure functions to
make code easier to understand and test.

### CODE REVIEW

**Comment by szanto90balazs** [comment]
:+1:

**Comment by knuton** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
