### PR TITLE
Easy Game UIs with React Native

### PR DESCRIPTION
**Pull request by jlongster**
React Native provides a good compromise for making native apps with a workflow similar to the web.
It's pretty easy to integrate React Native with any 2d or 3d game, and with the Cmd+R refresh
workflow combined with the declarative component style, it just became incredibly easy to make
game UIs!

I will dive into various strategies to integrate React Native with games. I will show how to
sync up the UI with game state, and go into details of the JavaScript and Objective-C bridge.

### CODE REVIEW

**Comment by SanderSpies** [comment]
+1

**Comment by nuc** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by arnihermann** [comment]
+1

**Comment by mzabriskie** [comment]
👍

**Comment by plasticine** [comment]
:+1:

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by stuartleigh** [comment]
:+1:

**Comment by fdecampredon** [comment]
:+1:

**Comment by joshschumacher** [comment]
+1, would love to hear more about this - I've been playing with React Native for writing basic games; it seems very promising.

**Comment by sejoker** [comment]
:+1:

**Comment by cgbystrom** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
