### PR TITLE
Relay: An Application Framework For React

### PR DESCRIPTION
**Pull request by josephsavona**
Relay is a new framework from Facebook that enables declarative data fetching & updates for React applications. Relay components use GraphQL to specify their data requirements, and compose together to form truly modular applications. This talk will explore the problems Relay solves, its architecture and the query lifecycle, and how can you use Relay to build more scalable apps. We’ll also see examples of how Relay powers applications as complex as the Facebook News Feed.

### CODE REVIEW

**Comment by vjeux** [comment]
:+1: :+1: :+1:

**Comment by emmenko** [comment]
:+1:

**Comment by nuc** [comment]
:+1:

**Comment by arnihermann** [comment]
+1

**Comment by fdecampredon** [comment]
:+1:

**Comment by joshschumacher** [comment]
:+1:

**Comment by jergason** [comment]
yupyupyup

**Comment by sejoker** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
