### PR TITLE
How React & Flux Turn Applications Into Extensible Platforms

### PR DESCRIPTION
**Pull request by emorikawa**
Chrome is great, but 3rd party extensions make it better. The iPhone is great, but apps make it better. Your React-app may be great, but imagine if you could safely and robustly allow 3rd party extensions to
enhance it.

We'll talk about specific features of React & Flux, React CSS, programming design patterns, and custom libraries, which can turn a static application into a dynamic platform that an ecosystem of developers can build on top of.

We've built a highly-extensible desktop email client with React & Flux on Atom Shell, and we'll also show concrete examples of where these tools enabled a 3rd party ecosystem of email plugins.

Our goal is for you to take away how to use React to be more than just great application developers, but now great platform developers as well.

[How React & Flux Turn Applications Into Extensible Platforms](http://www.youtube.com/watch?v=rccmUc1bQ4o)

### CODE REVIEW

**Comment by emorikawa** [comment]
If you want to read more about the specific project we're doing this for, check out: https://www.nilas.com/blog/splitting-the-atom

**Comment by fisherwebdev** [comment]
:+1:

**Comment by zackify** [comment]
+1!

**Comment by conchan** [comment]
:+1:!

**Comment by KartikTalwar** [comment]
:+1:

**Comment by mrcaps** [comment]
+1 - this looks fantastic!

**Comment by chris-ramon** [comment]
:+1:

**Comment by matma** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Pull request merged**
