### PR TITLE
become-a-frontend-superhero

### PR DESCRIPTION
**Pull request by robbestad**
Building a web app these days is not for the faint hearted. Luckily, we've got a range of superpowers available to us. I'll show you how to harness them.

In short, in this talk I'll show everything a frontend developer needs to know to develop awesome React apps.

### CODE REVIEW

**Comment by ibjohansen** [comment]
:+1: Looking great, hope you'll get this approved!

**Comment by mhoel** [comment]
Interesting topic! Hope you get accepted!

**Comment by kennep** [comment]
:+1: This looks really interesting :-)

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
