### PR TITLE
Patterns of Isomorphic React on the JVM

### PR DESCRIPTION
**Pull request by msolli**
Sometimes developing modern JS apps can feel like we've taken two steps forward and one step back. SEO takes a hit, the initial load can be a pain for users, and progressive enhancement goes out the window. The prospect of rendering the JS app on the server and serving up HTML on the initial request promises to solve these problem.

The JVM ships with a new JS runtime (Nashorn) that performs reasonably well, even compared to Node.js. It enables existing webapps on the JVM to benefit from server-side rendering. You can move your whole view layer into React. In this talk we'll explore patterns for running your React app on Nashorn. We'll discuss how to bundle up and load you JS into Nashorn, and some performance implications. We'll look at the Flux pattern and how to get data efficiently across language boundaries and into stores on the server. Finally we'll see how to get routing right in an isomorphic app.

Hope to see you in Paris!

### CODE REVIEW

**Comment by torarnek** [comment]
:+1:

**Comment by Andersos** [comment]
:+1:

**Comment by lottej** [comment]
+1

**Comment by krrm** [comment]
+1

**Comment by nicolaihoge** [comment]
+1

**Comment by cyberglot** [comment]
:+1:

**Comment by kevinrobinson** [comment]
:+1:

**Comment by stigkj** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
