### PR TITLE
The State of Animation in React

### PR DESCRIPTION
**Pull request by chenglou**
A talk on the past, the present and the future of animation, and the place React can potentially take in this. I will be focusing on a few experiments on animation I've done, specifically: react-tween-state, react-state-stream and some unreleased transition-group related thoughts and work.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
:+1:

**Comment by gurdasnijor** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by plasticine** [comment]
:+1:

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by Kaiserbald0** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by stuartleigh** [comment]
:+1:

**Comment by fdecampredon** [comment]
:+1:

**Comment by NicoVerkest** [comment]
+1

**Comment by jlongster** [comment]
👍

**Comment by sejoker** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by lenaschoenburg** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1: :+1: :+1:

**Pull request merged**
