### PR TITLE
Beyond renderToString(): Optimizing Server Rendering

### PR DESCRIPTION
**Pull request by redfin-sasha-aickin**
One of React's most alluring promises is that of isomorphic JavaScript through the use of `React.renderToString()`. However, that's only the beginning of what we need to write server-side React that is truly fast for our users. In this talk, we'll answer:
- What are the performance bottlenecks with server-side React?
- How can we parallelize browser painting and server rendering to make sure that time to first browser paint is not blocked by React rendering?
- How can we pipeline data to the client in an efficient way?
- How can we make single-page applications that load code progressively while rendering server-side for first page load?
- How will performance of server-side React rendering change as we move to HTTP/2?

We will share both theoretical and practical tips we've learned over the course of implementing a framework for fast React server rendering, and we plan to open-source our framework in time for ReactEurope.

### CODE REVIEW

**Comment by nuc** [comment]
:+1:

**Comment by KyleAMathews** [comment]
:+1:

**Comment by chris-ramon** [comment]
:+1:

**Comment by massimiliano-mantione** [comment]
:+1:+1

**Comment by 0xjocke** [comment]
+1

**Comment by mridgway** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
