### PR TITLE
Back to Text UI

### PR DESCRIPTION
**Pull request by azproduction**
```
     ____             _      _
    | __ )  __ _  ___| | __ | |_ ___
    |  _ \ / _` |/ __| |/ / | __/ _ \
    | |_) | (_| | (__|   <  | || (_) |
    |____/ \__,_|\___|_|\_\  \__\___/
    |_   _|____  _| |_  | | | |_ _|
      | |/ _ \ \/ / __| | | | || |
      | |  __/>  <| |_  | |_| || |
      |_|\___/_/\_\\__|  \___/|___|

    Paradoxically that today it is easier to create GUI than Text UI.
    Developer has an arsenal of different GUI libraries and layout engines.
    When one decides to write Terminal Text UI app he faces obstacles
    of Text UI DSL Library, imperative layouts, constantly increasing
    complexity and underdeveloped approaches.

    In this talk I will show you how to ask browser layout engine for help,
    how to avoid slavery of DSL and build declarative Text UI using only
    web-technologies like HTML, JS, CSS and React.

    ┌------------------┐ ┌--------┐
    | Approve Proposal | | Reject |
    └------------------┘ └--------┘
```

### CODE REVIEW

**Comment by isnifer** [comment]
+1

**Comment by metrofun** [comment]
:+1:

**Comment by flpvsk** [comment]
Would love to hear this one!

**Comment by gaearon** [comment]
That's cool. I was thinking of using something like this for my next article but haven't gotten to it yet.

**Comment by azproduction** [comment]
@gaearon thanks, I had [React-less prototype](http://azproduction.ru/html-tui/) for over a year, but with React it would be much better. As cool as React Native :)

**Comment by mindreframer** [comment]
like this one! +1

**Comment by esbullington** [comment]
+1

**Comment by markdalgleish** [comment]
:+1: brilliant

**Comment by jordwalke** [comment]
YES!

**Comment by gleb-svechnikov** [comment]
+1

**Comment by bitsofparag** [comment]
Awesome!

**Comment by dejitaiza** [comment]
Make it happen ! This sounds very interesting

**Comment by YuppY** [comment]
:+1:

**Comment by jergason** [comment]
this looks the raddest

**Comment by akovalev** [comment]
```
       /(|
      (  :
     __\  \  _____
   (____)  `|
  (____)|   |
   (____).__|
    (___)__.|_____
```

**Pull request merged**
