### PR TITLE
Synthetic Events Deep Dive

### PR DESCRIPTION
**Pull request by rickbeerendonk**
While elements take the spotlight in React's virtual DOM, the synthetic events are the backing vocals in the React band. There is not too much documentation while they are in fact an indispensable part of React.

Synthetic events are normalized between different browsers. This means you might have different behavior than you would normally see in a specific browser. On the other hand you might get events that are not originally supported, like mouse enter and mouse leave. Unfortunately not all events are supported, like HTML5's audio and video events. We'll see how to handle those in our React components. Testing synthetic events with Jest will also be handled.

The eventing system is an ingenious piece that translates native events into synthetic events using plugins. We cannot add our own plugins without forking React, but it is worth having a look at the internals to satisfy our curiosity.

This talk tries to deepen your knowledge about React events, its strong points, its weaknesses and its internals.

### CODE REVIEW

**Comment by chandu0101** [comment]
+1

**Comment by matma** [comment]
:+1:

**Comment by stuartleigh** [comment]
:+1:

**Comment by fdecampredon** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by gaearon** [comment]
:+1: just recently been looking at the implementation more closely, it really deserves more spotlight

**Comment by pletcher** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
