### PR TITLE
Improving Your Workflow With Code Transformation

### PR DESCRIPTION
**Pull request by sebmck**
Most React developers already use a build pipeline to transform their JSX into vanilla JavaScript. This is usually under-utilised only doing basic transformations such as concatenation, minification and linting.

In this talk, Sebastian will go over how this already existing infrastructure can be further utilised to perform even more significant code transformations such as transpilation, optimisation, profiling and more, reducing bugs, making your code faster and you as a developer more productive and happy.

### CODE REVIEW

**Comment by gaearon** [comment]
Yay!

**Comment by gabrielecirulli** [comment]
I would love to see this, :+1:

**Comment by antn** [comment]
I'd love to see this. Seb's work on 6to5 is awesome, and I'm sure this talk will be very interesting and informative :+1:

**Comment by ondrek** [comment]
Nice!

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by jamiebuilds** [comment]
:+1:

**Comment by SanderSpies** [comment]
:+1:

**Comment by ash47** [comment]
:+1: 9/10 or 10/10 with rice.

**Comment by andrewmcwatters** [comment]
:+1:

**Comment by arnihermann** [comment]
+1

**Comment by mzabriskie** [comment]
👍

**Comment by torarnek** [comment]
:+1:

**Comment by KyleAMathews** [comment]
:+1:

**Comment by gurdasnijor** [comment]
:+1:

**Comment by enginoid** [comment]
+1

**Comment by knuton** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by sejoker** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by jamiebuilds** [comment]
:tada:

**Comment by sebmck** [comment]
Thank you @patcito and everyone else involved, absolutely honoured!

**Pull request merged**
