### PR TITLE
Making React Reactive with Bacon

### PR DESCRIPTION
**Pull request by jackofseattle**
React syncs the state of your components to the DOM. But what about syncing the state of your data to your components? Reactive programming using BaconJS is the perfect way to propagate changes from your data directly to your DOM and back again.
This presentation will show how the reactive programing paradigm can help us greatly simplify the Flux architecture for fun and for profit.

### CODE REVIEW

**Comment by phyrisrose** [comment]
+1

**Comment by keipes** [comment]
:+1:

**Comment by ironosity** [comment]
Coming from a framework with 2-way data binding built in (angular), this sounds like an awesome idea!
:+1:

**Comment by johnabender** [comment]
+1

**Comment by davidandrus** [comment]
+1

**Comment by khuisman** [comment]
+1

**Comment by arian** [comment]
:+1:

**Comment by joshschumacher** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
