### PR TITLE
DB-Backed UI's with Sul - Crazy Experiments, Tools, & Findings

### PR DESCRIPTION
**Pull request by sgrove**
React pushed for simplicity so effectively, while staying so small, that it's enabled a whole new field of experiments in UI architecture.

In this talk, we look at a Sul, a new way of managing state in a React client via an in-memory, immutable database called DataScript. With Sul, instead of local state and multiple stores (normal React components & Flux) or narrowing scope (ClojureScript's Om components), we use database-queries against a single, centralized store to power components. Multiple components with no structural ancestor relationship can query against a central store and derive custom views, and if a transaction invalidates the view, the components are independently re-rendered.

Centralized stores and declarative db-queries also open up huge tooling possibilities - a designer can edit the query for a component in-browser and immediately see the change, entire user sessions can be captured and replayed for debugging and testing, and reusability falls out almost for free.

No abstraction is without its tradeoffs, however. We'll also cover some of the disadvantages and challenges of this approach so far, with an eye towards future areas of exploration and possibilities.

### CODE REVIEW

**Comment by chenglou** [comment]
:+1:

**Comment by KyleAMathews** [comment]
:+1:

**Comment by tadruj** [comment]
:+1:

**Comment by rokgregoric** [comment]
👍👍

**Comment by mihar** [comment]
:+1:

**Comment by kevinrobinson** [comment]
:+1:

**Comment by jlongster** [comment]
👍

**Comment by sejoker** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
