### PR TITLE
Animating with React

### PR DESCRIPTION
**Pull request by stefanRitter**
Animations can turn a mundane functional interface into a fully immersive experience. They make apps more intuitive and easier to navigate by helping users understand the context of where they are within our applications. Especially since the introduction of Material Design and Facebook’s Paper have expectations towards animations and transitions only grown - and rightly so. On the web platform, however, animations can quickly turn into an untestable setTimeout() nightmare.

In this talk, I’ll cover how React gives us a unique advantage when animating because it doesn't trash the DOM on state changes, re-rendering, or even navigation. How can we utilize ReactTransitions to implement maintainable performative animations? What are the pros and cons of animating with CSS, SVG, or element.animate() in React? How best to animate draggable objects? And finally, how does React compare to ng-animate and famo.us?

### CODE REVIEW

**Comment by nuc** [comment]
:+1:

**Comment by gaearon** [comment]
Would be great to also cover experimental approaches like https://github.com/chenglou/react-state-stream!

**Comment by stefanRitter** [comment]
@gaearon nice one! there are others like
https://github.com/chenglou/react-tween-state and velocity.js integration too that I'm looking into. @chenglou is also on the speaker list

**Comment by chenglou** [comment]
Aaaaah damn, I was thinking of talking about this actually... humm...

**Comment by podo** [comment]
:+1:

**Comment by kevinrobinson** [comment]
:+1:

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
