### PR TITLE
An Elm-inspired React architecture

### PR DESCRIPTION
**Pull request by leoasis**
Elm is a FRP language that compiles to Javascript. It’s creator, Evan Czaplicki, writes about a really simple pattern that naturally emerged when creating apps with Elm, that’s surprisingly powerful, here: https://github.com/evancz/elm-architecture-tutorial. Moreover, Elm’s redering technique uses vdom, which is inspired in turn by React. Should we come full circle?

In this talk, we’ll explain this architecture and explore how to bring it back to Javascript land using React, Immutable.js and the Flux dispatcher to provide a new way to create complex UIs. No need for using Stores, cursors or learn new concepts. If you know React and functions, you got all you need!

### CODE REVIEW

**Comment by emmenko** [comment]
:+1:

**Comment by gaearon** [comment]
:+1: I suspect React can borrow something from Elm, would love to learn more about it.

**Comment by jirivrany** [comment]
Sounds good. Would like to hear more.

**Comment by 0xjocke** [comment]
+1

**Comment by gianu** [comment]
:+1:

**Comment by szanto90balazs** [comment]
:+1:

**Comment by laszlopandy** [comment]
+1

**Comment by kevinrobinson** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by chantastic** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
