### PR TITLE
Rediscovering CSS best practices, the juggler way.

### PR DESCRIPTION
**Pull request by javpaw**
If I've learned anything from React is that  ‘best practices’ are not set in stone, they evolve, transform, disappear and suddenly out of out of nowhere they are back (Hi again, Inline CSS). Given the new posibilities that React bring us; What would be the best practices to work with the visual part of the components? How can we discover the best practices to deal with the visual complexity of a web application?

To try to answer this question, I'm starting a project called Component Juggler that  allows me to quickly assess the visual result of my component in its diferent states and external constraints.

I'd like to join me in this little trip with the Juggler and let me show you how to create a small web application, one component at a time, while we use, missuse and contrast the current CSS best practices and discover our own 'best practices' and the correct level of abstraction that work for our components and our web Application.

### CODE REVIEW

**Comment by javpaw** [comment]
A short video introducing the tool I'm developing and  a small example [Here](https://www.youtube.com/watch?v=54QbVkWlvTA), sorry for the quality, I'll upload another video with more quality soon.

**Comment by morenoh149** [comment]
:+1:  this sounds like a great way to quickly compare how your component will look in different circumstances.

**Comment by matma** [comment]
:+1:

**Comment by BerkeleyTrue** [comment]
Pretty Sweet! Can't to use this on my projects.

**Comment by javpaw** [comment]
I just uploaded a new video with better sound an shorter: http://youtu.be/yipM7CABoRk.
The code is not open sourced because it's a fast prototype to get some feedback but if somebody want it or want to start helping please let me know.
Also, What do you guys think of this approach?

**Comment by BerkeleyTrue** [comment]
I would like to help out.

**Comment by gabssnake** [comment]
:+1:

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a douzen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
