### PR TITLE
Going Mobile with React

### PR DESCRIPTION
**Pull request by JedWatson**
React.js is changing the way developers think about mobile app development, especially with the recent announcement of React Native. However, in many ways hybrid (web + mobile) app development is here to stay for a large number of mobile apps.

Everyone's heard "you can't build a native experience in a web view". We disagree. You just have to know the right tricks. And when you do, the web becomes an incredibly powerful platform for delivering amazing user experience using the technology you know.

At Thinkmill in Sydney, over the course of developing several commercial apps, we've experienced the power of using ReactJS for mobile apps built on web technology, and developed a framework we call TouchstoneJS (which Tom Occhino called "the best looking and feeling implementation of this that I've seen" during the Q&A session at React Conf) to share this capability with developers around the world.

In this talk I'll share what we've learned and how we've approached the unique challenges of mobile web apps - with tools that are useful to all developers building touch interfaces with React, as well as a walkthrough of our development process and framework.

I'll also talk about what you can do with the web platform that you can't with native apps, and even React Native.

### CODE REVIEW

**Comment by revolunet** [comment]
+1 :)

**Comment by gurdasnijor** [comment]
+1

**Comment by estilles** [comment]
+1

**Comment by Nicktho** [comment]
+1!

**Comment by BorisBozic** [comment]
Giddy up. +1

**Comment by Rob-Morris** [comment]
+1

**Comment by jossmac** [comment]
:+1: I would love to see this

**Comment by nkbt** [comment]
+1

**Comment by chandu0101** [comment]
+1

**Comment by sejoker** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by KeKs0r** [comment]
I am monitoring touchstone since a while and would love to see a talk about it :+1:

**Pull request merged**
