### PR TITLE
Added "backbone to react with love" talk.

### PR DESCRIPTION
**Pull request by byrichardpowell**
Thanks for creating such an awesome library :-)

### CODE REVIEW

**Comment by pootsbook** [comment]
Nice, :+1:

**Comment by alexgibson** [comment]
+1 :+1:

**Comment by sage-oli-wood** [comment]
That looks like a great talk +1

**Comment by benbowler** [comment]
+1 from me.

**Comment by roxana-cristea** [comment]
+1 :+1:

**Comment by samlambert** [comment]
:+1:

**Comment by kevprice** [comment]
+1 :+1:

**Comment by nuc** [comment]
:+1:

**Comment by 0x-r4bbit** [comment]
+1

**Comment by cburgdorf** [comment]
+1

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn't an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Comment by byrichardpowell** [comment]
Good luck with the conference, I can't wait!

**Pull request closed without merging**
