### PR TITLE
Keeping it simple: React & just a spreadsheet

### PR DESCRIPTION
**Pull request by 0x0ece**
Imagine a searchable product list with a few thousand items to
manage that uses only a spreadsheet as its database...

### CODE REVIEW

**Comment by esbullington** [comment]
+1

**Comment by 0x0ece** [comment]
Thanks @esbullington!

**Comment by davidevernizzi** [comment]
+1 for me too

**Comment by dev-ennova** [comment]
+1

**Comment by nax83** [comment]
+1

**Comment by brisma** [comment]
+1

**Comment by psmiraglia** [comment]
+1

**Comment by 0x0ece** [comment]
Woah... thanks to everybody!

**Comment by matma** [comment]
:+1:

**Comment by 0x0ece** [comment]
Thanks @matma

**Comment by jlongster** [comment]
👍

**Comment by 0x0ece** [comment]
Great @jlongster!

**Comment by 0x0ece** [comment]
BTW, an update on the theme of keeping it simple and using spreadsheets (in this case csv), an analysis of the Oscars 2015 on Twitter:
http://ecesena.github.io/oscars2015/

Code is also available:
http://github.com/ecesena/oscars2015

**Comment by patcito** [comment]
Thank you for taking your time and submitting your proposal. We have received close to a 100 and had to select only a dozen of them. It wasn’t an easy task and we're sorry that yours didn't make the cut. If you are still interested in coming and talk, there will be a lightning talk session during the conf in front of the whole audience with a great prize for the best talk, we will post more details soon. Cheers, Patrick.

**Pull request closed without merging**
