### PR TITLE
Live React: Hot Reloading with Time Travel

### PR DESCRIPTION
**Pull request by gaearon**
React’s unique strength is bringing to JavaScript development some of the benefits previously exclusive to more radically functional languages such as Elm and ClojureScript, without forcing you to completely eschew local state or rewrite code with exclusively immutable data structures.

In this talk, Dan will demonstrate how React can be used together with Webpack Hot Module Replacement to create a live editing environment with time travel that supercharges your debugging experience and transforms the way you work on real apps every day.

### CODE REVIEW

**Comment by kossnocorp** [comment]
:+1:

**Comment by SanderSpies** [comment]
+1

**Comment by vjeux** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by patcito** [comment]
:+1: :+1: :+1:

**Comment by gurdasnijor** [comment]
:+1:  x ∞

**Comment by sokra** [comment]
:+1:

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by fisherwebdev** [comment]
:+1:

**Comment by rickbeerendonk** [comment]
:+1:

**Comment by arnihermann** [comment]
+1

**Comment by mzabriskie** [comment]
👍

**Comment by massimiliano-mantione** [comment]
:+1:+1

**Comment by fdecampredon** [comment]
:+1:

**Comment by jkimbo** [comment]
:+1:

**Comment by jlongster** [comment]
👍

**Comment by sejoker** [comment]
:+1:

**Comment by markdalgleish** [comment]
:+1: YES!

**Comment by chantastic** [comment]
:+1:

**Comment by gaearon** [comment]
Thanks.

**Comment by gaearon** [comment]
Thanks to everyone who expressed their support.
You can watch the talk now: https://www.youtube.com/watch?v=xsSnOQynTHs

**Comment by chicoxyzzy** [comment]
:+1: great talk Dan!

**Comment by gurdasnijor** [comment]
@gaearon Awesome talk!

**Pull request merged**
